/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated/discovery'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AuthenticatedWatchlistsRouteImport } from './routes/_authenticated/watchlists'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs/index'
import { Route as AuthenticatedRunsIdRouteImport } from './routes/_authenticated/runs/$id'
import { Route as AuthenticatedScriptsIndexRouteImport } from './routes/_authenticated/scripts/index'
import { Route as AuthenticatedScriptsIdRouteImport } from './routes/_authenticated/scripts/$id'
import { Route as AuthenticatedScriptsComposerRouteImport } from './routes/_authenticated/scripts/composer'
import { Route as AuthenticatedStocksIndexRouteImport } from './routes/_authenticated/stocks/index'
import { Route as AuthenticatedStocksIdRouteImport } from './routes/_authenticated/stocks/$id'
import { Route as AuthenticatedStoriesIndexRouteImport } from './routes/_authenticated/stories/index'
import { Route as AuthenticatedStoriesIdRouteImport } from './routes/_authenticated/stories/$id'
import { Route as ApiPublicHooksSchedulerTickRouteImport } from './routes/api/public/hooks/scheduler-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistsRoute = AuthenticatedWatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsIdRoute = AuthenticatedRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsIndexRoute =
  AuthenticatedScriptsIndexRouteImport.update({
    id: '/scripts/',
    path: '/scripts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScriptsIdRoute = AuthenticatedScriptsIdRouteImport.update({
  id: '/scripts/$id',
  path: '/scripts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsComposerRoute =
  AuthenticatedScriptsComposerRouteImport.update({
    id: '/scripts/composer',
    path: '/scripts/composer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStocksIndexRoute =
  AuthenticatedStocksIndexRouteImport.update({
    id: '/stocks/',
    path: '/stocks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStocksIdRoute = AuthenticatedStocksIdRouteImport.update({
  id: '/stocks/$id',
  path: '/stocks/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoriesIndexRoute =
  AuthenticatedStoriesIndexRouteImport.update({
    id: '/stories/',
    path: '/stories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoriesIdRoute = AuthenticatedStoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSchedulerTickRoute =
  ApiPublicHooksSchedulerTickRouteImport.update({
    id: '/api/public/hooks/scheduler-tick',
    path: '/api/public/hooks/scheduler-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/market': typeof AuthenticatedMarketRoute
  '/research': typeof AuthenticatedResearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/watchlists': typeof AuthenticatedWatchlistsRoute
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/scripts/composer': typeof AuthenticatedScriptsComposerRoute
  '/stocks/$id': typeof AuthenticatedStocksIdRoute
  '/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
  '/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/stocks/': typeof AuthenticatedStocksIndexRoute
  '/stories/': typeof AuthenticatedStoriesIndexRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/market': typeof AuthenticatedMarketRoute
  '/research': typeof AuthenticatedResearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/watchlists': typeof AuthenticatedWatchlistsRoute
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/scripts/composer': typeof AuthenticatedScriptsComposerRoute
  '/stocks/$id': typeof AuthenticatedStocksIdRoute
  '/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
  '/scripts': typeof AuthenticatedScriptsIndexRoute
  '/stocks': typeof AuthenticatedStocksIndexRoute
  '/stories': typeof AuthenticatedStoriesIndexRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/_authenticated/watchlists': typeof AuthenticatedWatchlistsRoute
  '/_authenticated/runs/$id': typeof AuthenticatedRunsIdRoute
  '/_authenticated/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/_authenticated/scripts/composer': typeof AuthenticatedScriptsComposerRoute
  '/_authenticated/stocks/$id': typeof AuthenticatedStocksIdRoute
  '/_authenticated/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
  '/_authenticated/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/_authenticated/stocks/': typeof AuthenticatedStocksIndexRoute
  '/_authenticated/stories/': typeof AuthenticatedStoriesIndexRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/candidates'
    | '/dashboard'
    | '/discovery'
    | '/library'
    | '/market'
    | '/research'
    | '/settings'
    | '/sources'
    | '/watchlists'
    | '/runs/$id'
    | '/scripts/$id'
    | '/scripts/composer'
    | '/stocks/$id'
    | '/stories/$id'
    | '/runs/'
    | '/scripts/'
    | '/stocks/'
    | '/stories/'
    | '/api/public/hooks/scheduler-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/candidates'
    | '/dashboard'
    | '/discovery'
    | '/library'
    | '/market'
    | '/research'
    | '/settings'
    | '/sources'
    | '/watchlists'
    | '/runs/$id'
    | '/scripts/$id'
    | '/scripts/composer'
    | '/stocks/$id'
    | '/stories/$id'
    | '/runs'
    | '/scripts'
    | '/stocks'
    | '/stories'
    | '/api/public/hooks/scheduler-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/candidates'
    | '/_authenticated/dashboard'
    | '/_authenticated/discovery'
    | '/_authenticated/library'
    | '/_authenticated/market'
    | '/_authenticated/research'
    | '/_authenticated/settings'
    | '/_authenticated/sources'
    | '/_authenticated/watchlists'
    | '/_authenticated/runs/$id'
    | '/_authenticated/scripts/$id'
    | '/_authenticated/scripts/composer'
    | '/_authenticated/stocks/$id'
    | '/_authenticated/stories/$id'
    | '/_authenticated/runs/'
    | '/_authenticated/scripts/'
    | '/_authenticated/stocks/'
    | '/_authenticated/stories/'
    | '/api/public/hooks/scheduler-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSchedulerTickRoute: typeof ApiPublicHooksSchedulerTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlists': {
      id: '/_authenticated/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof AuthenticatedWatchlistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs/$id': {
      id: '/_authenticated/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AuthenticatedRunsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts/': {
      id: '/_authenticated/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AuthenticatedScriptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts/$id': {
      id: '/_authenticated/scripts/$id'
      path: '/scripts/$id'
      fullPath: '/scripts/$id'
      preLoaderRoute: typeof AuthenticatedScriptsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts/composer': {
      id: '/_authenticated/scripts/composer'
      path: '/scripts/composer'
      fullPath: '/scripts/composer'
      preLoaderRoute: typeof AuthenticatedScriptsComposerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stocks/': {
      id: '/_authenticated/stocks/'
      path: '/stocks'
      fullPath: '/stocks/'
      preLoaderRoute: typeof AuthenticatedStocksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stocks/$id': {
      id: '/_authenticated/stocks/$id'
      path: '/stocks/$id'
      fullPath: '/stocks/$id'
      preLoaderRoute: typeof AuthenticatedStocksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/': {
      id: '/_authenticated/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof AuthenticatedStoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/$id': {
      id: '/_authenticated/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof AuthenticatedStoriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/scheduler-tick': {
      id: '/api/public/hooks/scheduler-tick'
      path: '/api/public/hooks/scheduler-tick'
      fullPath: '/api/public/hooks/scheduler-tick'
      preLoaderRoute: typeof ApiPublicHooksSchedulerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedWatchlistsRoute: typeof AuthenticatedWatchlistsRoute
  AuthenticatedRunsIdRoute: typeof AuthenticatedRunsIdRoute
  AuthenticatedScriptsIdRoute: typeof AuthenticatedScriptsIdRoute
  AuthenticatedScriptsComposerRoute: typeof AuthenticatedScriptsComposerRoute
  AuthenticatedStocksIdRoute: typeof AuthenticatedStocksIdRoute
  AuthenticatedStoriesIdRoute: typeof AuthenticatedStoriesIdRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
  AuthenticatedScriptsIndexRoute: typeof AuthenticatedScriptsIndexRoute
  AuthenticatedStocksIndexRoute: typeof AuthenticatedStocksIndexRoute
  AuthenticatedStoriesIndexRoute: typeof AuthenticatedStoriesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedWatchlistsRoute: AuthenticatedWatchlistsRoute,
  AuthenticatedRunsIdRoute: AuthenticatedRunsIdRoute,
  AuthenticatedScriptsIdRoute: AuthenticatedScriptsIdRoute,
  AuthenticatedScriptsComposerRoute: AuthenticatedScriptsComposerRoute,
  AuthenticatedStocksIdRoute: AuthenticatedStocksIdRoute,
  AuthenticatedStoriesIdRoute: AuthenticatedStoriesIdRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
  AuthenticatedScriptsIndexRoute: AuthenticatedScriptsIndexRoute,
  AuthenticatedStocksIndexRoute: AuthenticatedStocksIndexRoute,
  AuthenticatedStoriesIndexRoute: AuthenticatedStoriesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSchedulerTickRoute: ApiPublicHooksSchedulerTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
