CREATE TABLE public.universe_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  market text NOT NULL CHECK (market IN ('US','India')),
  tier text NOT NULL CHECK (tier IN ('CORE_50','DYNAMIC_50')),
  ticker text NOT NULL,
  name text NOT NULL,
  sector text,
  exchange text,
  rank integer,
  score numeric,
  reason text,
  company_id uuid REFERENCES public.companies(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  computed_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (market, tier, ticker)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.universe_members TO authenticated;
GRANT ALL ON public.universe_members TO service_role;

ALTER TABLE public.universe_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view universe members"
  ON public.universe_members FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL);
CREATE POLICY "Authenticated users can manage universe members"
  ON public.universe_members FOR ALL TO authenticated USING (false) WITH CHECK (false);

CREATE TRIGGER update_universe_members_updated_at
  BEFORE UPDATE ON public.universe_members
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_universe_members_market_tier ON public.universe_members (market, tier, rank);

INSERT INTO public.universe_members (market, tier, ticker, name, sector, exchange, rank, reason) VALUES
('US','CORE_50','AAPL','Apple Inc.','Technology','NASDAQ',1,'US mega-cap core coverage'),
('US','CORE_50','MSFT','Microsoft Corporation','Technology','NASDAQ',2,'US mega-cap core coverage'),
('US','CORE_50','GOOGL','Alphabet Inc.','Communication Services','NASDAQ',3,'US mega-cap core coverage'),
('US','CORE_50','AMZN','Amazon.com, Inc.','Consumer Discretionary','NASDAQ',4,'US mega-cap core coverage'),
('US','CORE_50','NVDA','NVIDIA Corporation','Technology','NASDAQ',5,'US mega-cap core coverage'),
('US','CORE_50','META','Meta Platforms, Inc.','Communication Services','NASDAQ',6,'US mega-cap core coverage'),
('US','CORE_50','TSLA','Tesla, Inc.','Consumer Discretionary','NASDAQ',7,'US mega-cap core coverage'),
('US','CORE_50','BRK.B','Berkshire Hathaway Inc.','Financials','NYSE',8,'US mega-cap core coverage'),
('US','CORE_50','AVGO','Broadcom Inc.','Technology','NASDAQ',9,'US mega-cap core coverage'),
('US','CORE_50','LLY','Eli Lilly and Company','Health Care','NYSE',10,'US mega-cap core coverage'),
('US','CORE_50','JPM','JPMorgan Chase & Co.','Financials','NYSE',11,'US mega-cap core coverage'),
('US','CORE_50','V','Visa Inc.','Financials','NYSE',12,'US mega-cap core coverage'),
('US','CORE_50','UNH','UnitedHealth Group Incorporated','Health Care','NYSE',13,'US mega-cap core coverage'),
('US','CORE_50','XOM','Exxon Mobil Corporation','Energy','NYSE',14,'US mega-cap core coverage'),
('US','CORE_50','MA','Mastercard Incorporated','Financials','NYSE',15,'US mega-cap core coverage'),
('US','CORE_50','JNJ','Johnson & Johnson','Health Care','NYSE',16,'US mega-cap core coverage'),
('US','CORE_50','PG','The Procter & Gamble Company','Consumer Staples','NYSE',17,'US mega-cap core coverage'),
('US','CORE_50','COST','Costco Wholesale Corporation','Consumer Staples','NASDAQ',18,'US mega-cap core coverage'),
('US','CORE_50','HD','The Home Depot, Inc.','Consumer Discretionary','NYSE',19,'US mega-cap core coverage'),
('US','CORE_50','MRK','Merck & Co., Inc.','Health Care','NYSE',20,'US mega-cap core coverage'),
('US','CORE_50','ABBV','AbbVie Inc.','Health Care','NYSE',21,'US mega-cap core coverage'),
('US','CORE_50','CVX','Chevron Corporation','Energy','NYSE',22,'US mega-cap core coverage'),
('US','CORE_50','NFLX','Netflix, Inc.','Communication Services','NASDAQ',23,'US mega-cap core coverage'),
('US','CORE_50','AMD','Advanced Micro Devices, Inc.','Technology','NASDAQ',24,'US mega-cap core coverage'),
('US','CORE_50','PEP','PepsiCo, Inc.','Consumer Staples','NASDAQ',25,'US mega-cap core coverage'),
('US','CORE_50','ADBE','Adobe Inc.','Technology','NASDAQ',26,'US mega-cap core coverage'),
('US','CORE_50','CRM','Salesforce, Inc.','Technology','NYSE',27,'US mega-cap core coverage'),
('US','CORE_50','KO','The Coca-Cola Company','Consumer Staples','NYSE',28,'US mega-cap core coverage'),
('US','CORE_50','WMT','Walmart Inc.','Consumer Staples','NYSE',29,'US mega-cap core coverage'),
('US','CORE_50','BAC','Bank of America Corporation','Financials','NYSE',30,'US mega-cap core coverage'),
('US','CORE_50','TMO','Thermo Fisher Scientific Inc.','Health Care','NYSE',31,'US mega-cap core coverage'),
('US','CORE_50','ACN','Accenture plc','Technology','NYSE',32,'US mega-cap core coverage'),
('US','CORE_50','LIN','Linde plc','Materials','NASDAQ',33,'US mega-cap core coverage'),
('US','CORE_50','MCD','McDonald''s Corporation','Consumer Discretionary','NYSE',34,'US mega-cap core coverage'),
('US','CORE_50','CSCO','Cisco Systems, Inc.','Technology','NASDAQ',35,'US mega-cap core coverage'),
('US','CORE_50','ABT','Abbott Laboratories','Health Care','NYSE',36,'US mega-cap core coverage'),
('US','CORE_50','ORCL','Oracle Corporation','Technology','NYSE',37,'US mega-cap core coverage'),
('US','CORE_50','INTC','Intel Corporation','Technology','NASDAQ',38,'US mega-cap core coverage'),
('US','CORE_50','QCOM','QUALCOMM Incorporated','Technology','NASDAQ',39,'US mega-cap core coverage'),
('US','CORE_50','TXN','Texas Instruments Incorporated','Technology','NASDAQ',40,'US mega-cap core coverage'),
('US','CORE_50','DIS','The Walt Disney Company','Communication Services','NYSE',41,'US mega-cap core coverage'),
('US','CORE_50','GE','GE Aerospace','Industrials','NYSE',42,'US mega-cap core coverage'),
('US','CORE_50','CAT','Caterpillar Inc.','Industrials','NYSE',43,'US mega-cap core coverage'),
('US','CORE_50','BA','The Boeing Company','Industrials','NYSE',44,'US mega-cap core coverage'),
('US','CORE_50','UBER','Uber Technologies, Inc.','Industrials','NYSE',45,'US mega-cap core coverage'),
('US','CORE_50','PLTR','Palantir Technologies Inc.','Technology','NASDAQ',46,'US mega-cap core coverage'),
('US','CORE_50','MU','Micron Technology, Inc.','Technology','NASDAQ',47,'US mega-cap core coverage'),
('US','CORE_50','PFE','Pfizer Inc.','Health Care','NYSE',48,'US mega-cap core coverage'),
('US','CORE_50','GS','The Goldman Sachs Group, Inc.','Financials','NYSE',49,'US mega-cap core coverage'),
('US','CORE_50','SBUX','Starbucks Corporation','Consumer Discretionary','NASDAQ',50,'US mega-cap core coverage'),
('India','CORE_50','RELIANCE','Reliance Industries Limited','Energy','NSE',1,'India large-cap core coverage'),
('India','CORE_50','TCS','Tata Consultancy Services Limited','Information Technology','NSE',2,'India large-cap core coverage'),
('India','CORE_50','HDFCBANK','HDFC Bank Limited','Financials','NSE',3,'India large-cap core coverage'),
('India','CORE_50','ICICIBANK','ICICI Bank Limited','Financials','NSE',4,'India large-cap core coverage'),
('India','CORE_50','INFY','Infosys Limited','Information Technology','NSE',5,'India large-cap core coverage'),
('India','CORE_50','BHARTIARTL','Bharti Airtel Limited','Telecom','NSE',6,'India large-cap core coverage'),
('India','CORE_50','SBIN','State Bank of India','Financials','NSE',7,'India large-cap core coverage'),
('India','CORE_50','LT','Larsen & Toubro Limited','Industrials','NSE',8,'India large-cap core coverage'),
('India','CORE_50','ITC','ITC Limited','Consumer Staples','NSE',9,'India large-cap core coverage'),
('India','CORE_50','HINDUNILVR','Hindustan Unilever Limited','Consumer Staples','NSE',10,'India large-cap core coverage'),
('India','CORE_50','KOTAKBANK','Kotak Mahindra Bank Limited','Financials','NSE',11,'India large-cap core coverage'),
('India','CORE_50','AXISBANK','Axis Bank Limited','Financials','NSE',12,'India large-cap core coverage'),
('India','CORE_50','BAJFINANCE','Bajaj Finance Limited','Financials','NSE',13,'India large-cap core coverage'),
('India','CORE_50','MARUTI','Maruti Suzuki India Limited','Consumer Discretionary','NSE',14,'India large-cap core coverage'),
('India','CORE_50','M&M','Mahindra & Mahindra Limited','Consumer Discretionary','NSE',15,'India large-cap core coverage'),
('India','CORE_50','SUNPHARMA','Sun Pharmaceutical Industries Limited','Health Care','NSE',16,'India large-cap core coverage'),
('India','CORE_50','TATAMOTORS','Tata Motors Limited','Consumer Discretionary','NSE',17,'India large-cap core coverage'),
('India','CORE_50','TATASTEEL','Tata Steel Limited','Materials','NSE',18,'India large-cap core coverage'),
('India','CORE_50','NTPC','NTPC Limited','Utilities','NSE',19,'India large-cap core coverage'),
('India','CORE_50','POWERGRID','Power Grid Corporation of India Limited','Utilities','NSE',20,'India large-cap core coverage'),
('India','CORE_50','ONGC','Oil and Natural Gas Corporation Limited','Energy','NSE',21,'India large-cap core coverage'),
('India','CORE_50','COALINDIA','Coal India Limited','Energy','NSE',22,'India large-cap core coverage'),
('India','CORE_50','ASIANPAINT','Asian Paints Limited','Materials','NSE',23,'India large-cap core coverage'),
('India','CORE_50','TITAN','Titan Company Limited','Consumer Discretionary','NSE',24,'India large-cap core coverage'),
('India','CORE_50','ULTRACEMCO','UltraTech Cement Limited','Materials','NSE',25,'India large-cap core coverage'),
('India','CORE_50','WIPRO','Wipro Limited','Information Technology','NSE',26,'India large-cap core coverage'),
('India','CORE_50','HCLTECH','HCL Technologies Limited','Information Technology','NSE',27,'India large-cap core coverage'),
('India','CORE_50','TECHM','Tech Mahindra Limited','Information Technology','NSE',28,'India large-cap core coverage'),
('India','CORE_50','ADANIENT','Adani Enterprises Limited','Industrials','NSE',29,'India large-cap core coverage'),
('India','CORE_50','ADANIPORTS','Adani Ports and SEZ Limited','Industrials','NSE',30,'India large-cap core coverage'),
('India','CORE_50','JSWSTEEL','JSW Steel Limited','Materials','NSE',31,'India large-cap core coverage'),
('India','CORE_50','HINDALCO','Hindalco Industries Limited','Materials','NSE',32,'India large-cap core coverage'),
('India','CORE_50','GRASIM','Grasim Industries Limited','Materials','NSE',33,'India large-cap core coverage'),
('India','CORE_50','NESTLEIND','Nestle India Limited','Consumer Staples','NSE',34,'India large-cap core coverage'),
('India','CORE_50','BRITANNIA','Britannia Industries Limited','Consumer Staples','NSE',35,'India large-cap core coverage'),
('India','CORE_50','DRREDDY','Dr. Reddy''s Laboratories Limited','Health Care','NSE',36,'India large-cap core coverage'),
('India','CORE_50','CIPLA','Cipla Limited','Health Care','NSE',37,'India large-cap core coverage'),
('India','CORE_50','DIVISLAB','Divi''s Laboratories Limited','Health Care','NSE',38,'India large-cap core coverage'),
('India','CORE_50','APOLLOHOSP','Apollo Hospitals Enterprise Limited','Health Care','NSE',39,'India large-cap core coverage'),
('India','CORE_50','BAJAJFINSV','Bajaj Finserv Limited','Financials','NSE',40,'India large-cap core coverage'),
('India','CORE_50','SBILIFE','SBI Life Insurance Company Limited','Financials','NSE',41,'India large-cap core coverage'),
('India','CORE_50','HDFCLIFE','HDFC Life Insurance Company Limited','Financials','NSE',42,'India large-cap core coverage'),
('India','CORE_50','INDUSINDBK','IndusInd Bank Limited','Financials','NSE',43,'India large-cap core coverage'),
('India','CORE_50','EICHERMOT','Eicher Motors Limited','Consumer Discretionary','NSE',44,'India large-cap core coverage'),
('India','CORE_50','HEROMOTOCO','Hero MotoCorp Limited','Consumer Discretionary','NSE',45,'India large-cap core coverage'),
('India','CORE_50','BAJAJ-AUTO','Bajaj Auto Limited','Consumer Discretionary','NSE',46,'India large-cap core coverage'),
('India','CORE_50','TATACONSUM','Tata Consumer Products Limited','Consumer Staples','NSE',47,'India large-cap core coverage'),
('India','CORE_50','SHRIRAMFIN','Shriram Finance Limited','Financials','NSE',48,'India large-cap core coverage'),
('India','CORE_50','BPCL','Bharat Petroleum Corporation Limited','Energy','NSE',49,'India large-cap core coverage'),
('India','CORE_50','LTIM','LTIMindtree Limited','Information Technology','NSE',50,'India large-cap core coverage');